service: lambda-s3-sample-serverless
frameworkVersion: '2'
provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
package:
  exclude:
    - .git
    - .gitignore
    - docker.env
    - docker.env.sample
    - docker-compose.yml
    - Dockerfile.dev
